name: TheAccubin Code QA

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  phpstan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install dependencies
        run: composer install --no-progress --no-suggest --prefer-dist

      - name: Run PHPStan
        run: composer analyse

  cs-fixer:
    runs-on: ubuntu-latest
    needs: phpstan
    permissions:
      contents: write
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist

      - name: Run PHP-CS-Fixer
        run: composer fix

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add .
          git commit -m "style(php-cs-fixer): apply changes" || echo "No changes to commit"

      - name: Push changes
        run: git push origin HEAD:${{ github.ref }}
        if: success()
